window.tailwind = window.tailwind || {};
window.tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#007139",
        tertiary: "#565e74",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "on-surface-variant": "#3b4b3d",
        secondary: "#00629d",
        "secondary-container": "#00a2fd",
        "secondary-fixed-dim": "#98cbff",
        "outline-variant": "#b9cbb9",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        background: "#f7f9fb",
        "on-primary-fixed-variant": "#005228",
        error: "#ba1a1a",
        "surface-container-low": "#f2f4f6",
        "surface-tint": "#006d37",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-background": "#191c1e",
        "secondary-fixed": "#cfe5ff",
        "tertiary-fixed": "#dae2fd",
        "inverse-on-surface": "#eff1f3",
        surface: "#f7f9fb",
        "on-secondary-container": "#003558",
        "tertiary-container": "#d6def8",
        "on-surface": "#191c1e",
        "tertiary-fixed-dim": "#bec6e0",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        primary: "#006d37",
        "primary-container": "#00ff88",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#00210c",
        "on-secondary-fixed-variant": "#004a77",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#001d33",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-container": "#5a6178",
        outline: "#6a7b6c",
        "inverse-primary": "#00e479",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "primary-fixed": "#60ff99",
        "on-tertiary-fixed": "#131b2e",
        "surface-variant": "#e0e3e5",
        "surface-container-high": "#e6e8ea",
        "primary-fixed-dim": "#00e479",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        gutter: "24px",
        xs: "4px",
        md: "24px",
        xl: "80px",
        sm: "12px",
        base: "8px",
        lg: "48px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Sora"],
        "body-lg": ["Inter"],
        display: ["Sora"],
        "label-bold": ["Inter"],
        "headline-lg": ["Sora"],
        "headline-md": ["Sora"],
        "body-md": ["Inter"],
        caption: ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        display: ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-bold": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
};
